### ISSUE TITLE
bankingContainer Background image 

### ISSUE THREAD

**Issue by robwhitewick** [qbcore-redm-framework/qbr-banking#10]
The bankingContainer background url has apparently been deleted by discord [former link](https://cdn.discordapp.com/attachments/844604041514451004/880043379830952036/---4.jpg) causing transparent ui's such as this 
![image](https://user-images.githubusercontent.com/37089244/173239996-34e259d5-7cd5-4642-b251-84faf7cd58b1.png)

**Comment by RexShack** [comment]
PR created : https://github.com/qbcore-redm-framework/qbr-banking/pull/11

**Comment by robwhitewick** [comment]
fixed as of https://github.com/qbcore-redm-framework/qbr-banking/compare/fda9f1c094fc...2dd02ea911f1
