### ISSUE TITLE
SCRIPT ERROR: qbr-banking/server/server.lua line 241

### ISSUE THREAD

**Issue by RexShack** [qbcore-redm-framework/qbr-banking#8]
SCRIPT ERROR: @qbr-banking/server/server.lua:241: attempt to call a nil value (global 'createSavingsAccount')
![Screenshot 2022-02-06 090726](https://user-images.githubusercontent.com/76662933/152674380-b9fb4bed-e7b6-4312-a751-7454c9835fb2.jpg)

**Comment by mNm-server** [comment]
Issue has been fixed and resource has been updated
